on:
  workflow_dispatch:

jobs:
  my_build:
    runs-on: linux
    steps:
      - name: check docker
        run: docker -v





  # my_test:
  #   runs-on: linux




  # my_deploy:
  #   runs-on: Linux
