on:
  push:
    branches: dev
  workflow_dispatch:

jobs:
  my_build:
    runs-on: linux
    steps:
      - name: copy repos resources
        uses: actions/checkout@v3


  my_test:
    needs: my_build
    runs-on: linux
    steps:
      - name: create .env files from secrets
        run: |
          cat > .env << EOF
          POSTGRES_USER=${{ secrets.POSTGRES_USER}}
          POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD}}
          POSTGRES_DB=${{ secrets.POSTGRES_DB}}
      - name: check .env
        run: cat .env
      - name: create env for python
        run: |
          cd flaskproj
          cat > .env << EOF
          dbname1=${{ secrets.dbname1 }}
          user1=${{ secrets.user1 }}
          password1=${{ secrets.password1 }}
          host1=${{ secrets.host1 }}
      - name: check .env
        run: cat .env

      - name: compose up
        run : docker compose up -d
      - name: check conts
        run: docker ps -a


  check_apps:
    needs: my_test
    runs-on: linux
    steps:
      - name: run apps tests
        run: |
          echo "Проверка работы приложения"
          if curl -f http://localhost:${{ secrets.FLASK_PORT }}; 
          then
            echo "Web application is healthy"
          else
            echo "Web application health-check is failed"
            exit 1
          fi
      - name: run bd tests
        run: |
          pg_isready -h localhost -p 5432 -U ${{ secrets.POSTGRES_USER }}

      

  my_end:
    needs: check_apps
    runs-on: linux
    steps:
      - name: terminate all conts
        run: docker compose down


