on:
  push:
    branches: dev
  workflow_dispatch:

jobs:
  building:
    runs-on: linux
    steps:
      - name: copy repos resources
        uses: actions/checkout@v3
      - name: building env`s files for compose
        run: |
          cat > .env << EOF
          POSTGRES_USER=${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB=${{ secrets.POSTGRES_DB }}
      - name: building env`s files for python site
        run: |
          cd flaskproj
          cat > .env << EOF
          dbname1=${{ secrets.dbname1 }}
          user1=${{ secrets.user1 }}
          password1=${{ secrets.password1 }}
          host1=${{ secrets.host1 }}
      - name: compose up
        run : docker compose up -d
      - name: check conts
        run: docker ps -a



  health_check:
    needs: building
    runs-on: linux
    steps:
      - name: check flask site
        run: |
          echo "Проверка работы приложения"
          if curl -f http://localhost:${{ secrets.FLASK_PORT }}; 
          then
            echo "Web application is healthy"
          else
            echo "Web application health-check is failed"
            exit 1
          fi
      - name: check database 
        run: |
          if docker exec psgr pg_isready -U ${{ secrets.POSTGRES_USER }} > /dev/null 2>&1;
          then
            echo "PostgreSQL is ready"
          else
            echo "Application database connection failed"
            exit 1
          fi
      - name: check adminer
        run: |
          echo "Проверка работы СУБД"
          if curl -f http://localhost:${{ secrets.ADMINER_PORT }}; 
          then
            echo "DBS application is healthy"
          else
            echo "DBS application health-check is failed"
            exit 1
          fi

  comparison:
    runs-on: linux
    needs: health_check
    steps:
      - name: testing data consistency
        run: |
          DB_COUNT=$(docker exec psgr psql -U user -d mydata -t -A -c "SELECT COUNT(*) FROM products;")
          WEB_COUNT=$(curl -s -D /dev/null https://localhost:${{ secrets.FLASK_PORT }} | wc -l)
          if [ $DB_COUNT -eq $WEB_COUNT ];
          then
            echo "Data consistency test passed"
          else
            echo "Data consistency test failed"
            exit 1
          fi
      

  my_end:
    needs: comparison
    runs-on: linux
    steps:
      - name: terminate all conts
        run: docker compose down


